/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_client_Client */

#ifndef _Included_xreal_client_Client
#define _Included_xreal_client_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_client_Client
 * Method:    getConfigString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_client_Client_getConfigString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
