Document: xreal
Title: Debian xreal Manual
Author: <insert document author here>
Abstract: This manual describes what xreal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xreal/xreal.sgml.gz

Format: postscript
Files: /usr/share/doc/xreal/xreal.ps.gz

Format: text
Files: /usr/share/doc/xreal/xreal.text.gz

Format: HTML
Index: /usr/share/doc/xreal/html/index.html
Files: /usr/share/doc/xreal/html/*.html
