!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.colormap
#semantic main.view_origin
#semantic main.eta_ratio
#semantic main.fresnel_power
#semantic main.fresnel_scale
#semantic main.fresnel_bias
#var samplerCUBE colormap :  : texunit 0 : 1 : 1
#var float3 view_origin :  :  : 2 : 1
#var float3 eta_ratio :  :  : 3 : 1
#var float fresnel_power :  :  : 4 : 1
#var float fresnel_scale :  :  : 5 : 1
#var float fresnel_bias :  :  : 6 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
DECLARE view_origin;
DECLARE eta_ratio;
DECLARE fresnel_power;
DECLARE fresnel_scale;
DECLARE fresnel_bias;
ADDR R0.xyz, f[TEX0].xyzx, -view_origin.xyzx;
DP3R R0.w, R0.xyzx, R0.xyzx;
RSQR R0.w, R0.w;
DP3R R1.x, f[TEX1].xyzx, f[TEX1].xyzx;
RSQR R1.x, R1.x;
MULR R1.xyz, R1.x, f[TEX1].xyzx;
MULR R2.xyz, R0.w, R0.xyzx;
DP3R R1.w, -R2.xyzx, R1.xyzx;
MADR R2.w, -R1.w, R1.w, {1}.x;
DP3R R3.x, -R2.xyzx, R1.xyzx;
MULR R3.y, eta_ratio.x, eta_ratio.x;
MADR R2.w, -R3.y, R2.w, {1}.x;
SGTR H0.x, R2.w, {0}.x;
RSQR R2.w, |R2.w|;
RCPR R2.w, R2.w;
MULR R2.w, {1}.x, R2.w;
MADR R2.w, eta_ratio.x, R1.w, -R2.w;
MULR R4.xyz, R2.w, R1.xyzx;
MADR R4.xyz, eta_ratio.x, R2.xyzx, R4.xyzx;
MULR R4.xyz, R4.xyzx, H0.x;
TEX R4.x, R4.xyzx, TEX0, CUBE;
MOVX H0.x, R4.x;
MADR R1.w, -R3.x, R3.x, {1}.x;
DP3R R2.w, -R2.xyzx, R1.xyzx;
MULR R3.y, eta_ratio.y, eta_ratio.y;
MADR R1.w, -R3.y, R1.w, {1}.x;
SGTR H0.w, R1.w, {0}.x;
RSQR R1.w, |R1.w|;
RCPR R1.w, R1.w;
MULR R1.w, {1}.x, R1.w;
MADR R1.w, eta_ratio.y, R3.x, -R1.w;
MULR R3.xyz, R1.w, R1.xyzx;
MADR R3.xyz, eta_ratio.y, R2.xyzx, R3.xyzx;
MULR R3.xyz, R3.xyzx, H0.w;
TEX R3.y, R3.xyzx, TEX0, CUBE;
MOVX H0.y, R3.y;
MADR R1.w, -R2.w, R2.w, {1}.x;
MULR R3.x, eta_ratio.z, eta_ratio.z;
MADR R1.w, -R3.x, R1.w, {1}.x;
SGTR H0.w, R1.w, {0}.x;
RSQR R1.w, |R1.w|;
RCPR R1.w, R1.w;
MULR R1.w, {1}.x, R1.w;
MADR R1.w, eta_ratio.z, R2.w, -R1.w;
MULR R3.xyz, R1.w, R1.xyzx;
MADR R3.xyz, eta_ratio.z, R2.xyzx, R3.xyzx;
MULR R3.xyz, R3.xyzx, H0.w;
TEX R3.z, R3.xyzx, TEX0, CUBE;
MOVX H0.z, R3.z;
DP3R R1.w, R1.xyzx, R2.xyzx;
DP3R R2.x, R2.xyzx, R1.xyzx;
MULR R1.xyz, {2}.x, R1.xyzx;
MULR R1.xyz, R1.xyzx, R1.w;
MADR R1.xyz, R0.w, R0.xyzx, -R1.xyzx;
ADDR R2.x, {1}.x, -R2.x;
POWR R2.x, R2.x, fresnel_power.x;
TEX R0.xyz, R1.xyzx, TEX0, CUBE;
ADDX H1.xyz, R0.xyzx, -H0.xyzx;
MOVR R0.x, fresnel_bias.x;
MADR R0.x, R2.x, fresnel_scale.x, R0.x;
MADX H0.xyz, R0.x, H1.xyzx, H0.xyzx;
MOVR o[COLR].xyz, H0.xyzx;
MOVR o[COLR].w, {1}.x;
END
# 63 instructions, 5 R-regs, 2 H-regs.
# End of program
