!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.colormap
#var sampler2D colormap :  : texunit 0 : 1 : 1
#var float4 IN.color0 : $vin.COLOR0 : COL0 : 0 : 1
#var float2 IN.tex0 : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
TEMP R0;
TEMP R1;
TEX R0, fragment.texcoord[0], texture[0], 2D;
MOV R1.w, R0.w;
MUL R0.xyz, R0, fragment.color.primary;
MOV R1.xyz, R0;
MOV result.color, R1;
END
# 5 instructions, 2 R-regs, 0 H-regs.
# End of program
