!!ARBvp1.0
# ARB_vertex_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbvp1
# nv30vp backend compiling 'main' program
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbvp1
#program main
#semantic main.color
#var float4 color :  : c[0] : 1 : 1
#var float4 IN.position : $vin.ATTR0 : ATTR0 : 0 : 1
#var float4 IN.tex0 : $vin.ATTR8 : ATTR8 : 0 : 1
#var float4 main.position : $vout.POSITION : HPOS : -1 : 1
#var float4 main.tex0 : $vout.TEXCOORD0 : TEX0 : -1 : 1
#var float4 main.color0 : $vout.COLOR0 : COL0 : -1 : 1
ATTRIB v8 = vertex.attrib[8];
ATTRIB v0 = vertex.attrib[0];
PARAM c0 = program.local[0];
PARAM s263[4] = { state.matrix.texture[0] };
PARAM s259[4] = { state.matrix.mvp };
	DP4 result.position.x, s259[0], v0;
	DP4 result.position.y, s259[1], v0;
	DP4 result.position.z, s259[2], v0;
	DP4 result.position.w, s259[3], v0;
	DP4 result.texcoord[0].x, s263[0], v8;
	DP4 result.texcoord[0].y, s263[1], v8;
	DP4 result.texcoord[0].z, s263[2], v8;
	DP4 result.texcoord[0].w, s263[3], v8;
	MOV result.color.front.primary, c0;
END
# 9 instructions
# 0 temp registers
# End of program
