!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.colormap
#var sampler2D colormap :  : texunit 0 : 1 : 1
#var float4 IN.color0 : $vin.COLOR0 : COL0 : 0 : 1
#var float4 IN.tex0 : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
TEX R0, f[TEX0].xyxx, TEX0, 2D;
MOVR R1.w, R0.w;
MULR R0.xyz, R0.xyzx, f[COL0].xyzx;
MOVR R1.xyz, R0.xyzx;
MOVR o[COLR], R1;
END
# 5 instructions, 2 R-regs, 0 H-regs.
# End of program
