!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.diffusemap
#semantic main.bumpmap
#semantic main.lightmap
#semantic main.deluxemap
#semantic main.bump_scale
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D bumpmap :  : texunit 1 : 2 : 1
#var sampler2D lightmap :  : texunit 2 : 3 : 1
#var sampler2D deluxemap :  : texunit 3 : 4 : 1
#var float bump_scale :  : c[0] : 5 : 1
#var float4 IN.tex_diffuse : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 IN.tex_bump : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_light : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_deluxe : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var float3 IN.tangent : $vin.TEXCOORD5 : TEX5 : 0 : 1
#var float3 IN.binormal : $vin.TEXCOORD6 : TEX6 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD7 : TEX7 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
PARAM u0 = program.local[0];
PARAM c0 = {2, 0.5, 0, 0};
TEMP R0;
TEMP R1;
TEMP R2;
TEX R0.xyz, fragment.texcoord[3], texture[3], 2D;
TEX R1.xyz, fragment.texcoord[1], texture[1], 2D;
ADD R0.xyz, R0, -c0.y;
MUL R0.xyz, R0, c0.x;
ADD R1.xyz, R1, -c0.y;
MUL R1.xyz, R1, c0.x;
DP3 R0.w, fragment.texcoord[5], R0;
MOV R2.x, R0.w;
DP3 R0.w, fragment.texcoord[6], R0;
MOV R2.y, R0.w;
DP3 R0.x, fragment.texcoord[7], R0;
MOV R2.z, R0.x;
MOV R0.xy, R1;
MUL R0.w, R1.z, u0.x;
MOV R0.z, R0.w;
DP3 R0.w, R0, R0;
RSQ R0.w, R0.w;
MUL R0.xyz, R0.w, R0;
DP3 R0.w, R2, R2;
RSQ R0.w, R0.w;
MUL R2.xyz, R0.w, R2;
DP3_SAT R0.x, R0, R2;
TEX R1.xyz, fragment.texcoord[2], texture[2], 2D;
TEX R2, fragment.texcoord[0], texture[0], 2D;
MUL R0.xyz, R1, R0.x;
MUL R0.xyz, R2, R0;
MOV R2.xyz, R0;
MOV result.color, R2;
END
# 28 instructions, 3 R-regs, 0 H-regs.
# End of program
