!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.diffusemap
#semantic main.bumpmap
#semantic main.lightmap
#semantic main.deluxemap
#semantic main.bump_scale
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D bumpmap :  : texunit 1 : 2 : 1
#var sampler2D lightmap :  : texunit 2 : 3 : 1
#var sampler2D deluxemap :  : texunit 3 : 4 : 1
#var float bump_scale :  :  : 5 : 1
#var float4 IN.tex_diffuse : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 IN.tex_bump : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_light : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_deluxe : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var float3 IN.tangent : $vin.TEXCOORD5 : TEX5 : 0 : 1
#var float3 IN.binormal : $vin.TEXCOORD6 : TEX6 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD7 : TEX7 : 0 : 1
#var half4 main.color : $vout.COLOR : COL : -1 : 1
DECLARE bump_scale;
TEX R0.xyz, f[TEX3].xyxx, TEX3, 2D;
TEX R1.xyz, f[TEX1].xyxx, TEX1, 2D;
ADDR R0.xyz, R0.xyzx, -{0.5}.x;
MULR R0.xyz, R0.xyzx, {2}.x;
ADDR R1.xyz, R1.xyzx, -{0.5}.x;
MULR R1.xyz, R1.xyzx, {2}.x;
MOVR H0.xy, R1.xyxx;
MULR R0.w, R1.z, bump_scale.x;
MOVH H0.z, R0.w;
DP3H H0.w, H0.xyzx, H0.xyzx;
RSQH H0.w, H0.w;
MULH H0.xyz, H0.w, H0.xyzx;
DP3R R0.w, f[TEX5].xyzx, R0.xyzx;
MOVR R1.x, R0.w;
DP3R R0.w, f[TEX6].xyzx, R0.xyzx;
MOVR R1.y, R0.w;
DP3R R0.x, f[TEX7].xyzx, R0.xyzx;
MOVR R1.z, R0.x;
DP3R R0.x, R1.xyzx, R1.xyzx;
RSQR R0.x, R0.x;
MULR R1.xyz, R0.x, R1.xyzx;
DP3X_SAT H0.x, H0.xyzx, R1.xyzx;
TEX R0.xyz, f[TEX2].xyxx, TEX2, 2D;
TEX R1, f[TEX0].xyxx, TEX0, 2D;
MULX H0.xyz, R0.xyzx, H0.x;
MULX H0.xyz, R1.xyzx, H0.xyzx;
MOVR H1.w, R1.w;
MOVX H1.xyz, H0.xyzx;
MOVX o[COLH], H1;
END
# 29 instructions, 2 R-regs, 2 H-regs.
# End of program
