!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.diffusemap
#semantic main.bumpmap
#semantic main.heightmap
#semantic main.specularmap
#semantic main.lightmap
#semantic main.deluxemap
#semantic main.view_origin
#semantic main.bump_scale
#semantic main.height_scale
#semantic main.height_bias
#semantic main.specular_exponent
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D bumpmap :  : texunit 1 : 2 : 1
#var sampler2D heightmap :  : texunit 2 : 3 : 1
#var sampler2D specularmap :  : texunit 3 : 4 : 1
#var sampler2D lightmap :  : texunit 4 : 5 : 1
#var sampler2D deluxemap :  : texunit 5 : 6 : 1
#var float3 view_origin :  :  : 7 : 1
#var float bump_scale :  :  : 8 : 1
#var float height_scale :  :  : 9 : 1
#var float height_bias :  :  : 10 : 1
#var float specular_exponent :  :  : 11 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 IN.tex_diffuse_bump : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_height : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_specular : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var float4 IN.tex_light_deluxe : $vin.TEXCOORD4 : TEX4 : 0 : 1
#var float3 IN.tangent : $vin.TEXCOORD5 : TEX5 : 0 : 1
#var float3 IN.binormal : $vin.TEXCOORD6 : TEX6 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD7 : TEX7 : 0 : 1
#var half4 main.color : $vout.COLOR : COL : -1 : 1
DECLARE view_origin;
DECLARE bump_scale;
DECLARE height_scale;
DECLARE height_bias;
DECLARE specular_exponent;
TEX R0.xyz, f[TEX4].zwzz, TEX5, 2D;
TEX R1.x, f[TEX2].xyxx, TEX2, 2D;
ADDR R0.xyz, R0.xyzx, -{0.5}.x;
MULR R0.xyz, R0.xyzx, {2}.x;
ADDR R2.xyz, view_origin.xyzx, -f[TEX0].xyzx;
DP3R R0.w, f[TEX5].xyzx, R2.xyzx;
MOVR R3.x, R0.w;
DP3R R0.w, f[TEX6].xyzx, R2.xyzx;
MOVR R3.y, R0.w;
DP3R R0.w, f[TEX7].xyzx, R2.xyzx;
MOVR R3.z, R0.w;
DP3R R0.w, R3.xyzx, R3.xyzx;
RSQR R0.w, R0.w;
MULR R3.xyz, R0.w, R3.xyzx;
MOVR R0.w, height_bias.x;
MADR R0.w, R1.x, height_scale.x, R0.w;
DP3R R1.x, f[TEX5].xyzx, R0.xyzx;
MADR R2.xy, R0.w, R3.xyxx, f[TEX1].zwzz;
TEX R2.xyz, R2.xyxx, TEX1, 2D;
TEX R4.xyz, f[TEX4].xyxx, TEX4, 2D;
ADDR R2.xyz, R2.xyzx, -{0.5}.x;
MULR R2.xyz, R2.xyzx, {2}.x;
MOVR H0.xy, R2.xyxx;
MULR R1.w, R2.z, bump_scale.x;
MOVH H0.z, R1.w;
DP3H H0.w, H0.xyzx, H0.xyzx;
RSQH H0.w, H0.w;
MULH H0.xyz, H0.w, H0.xyzx;
DP3R R1.w, f[TEX6].xyzx, R0.xyzx;
MOVR R1.y, R1.w;
DP3R R0.x, f[TEX7].xyzx, R0.xyzx;
MOVR R1.z, R0.x;
DP3R R0.x, R1.xyzx, R1.xyzx;
RSQR R0.x, R0.x;
MULR R1.xyz, R0.x, R1.xyzx;
ADDX H1.xyz, R1.xyzx, R3.xyzx;
DP3X_SAT H0.w, H0.xyzx, R1.xyzx;
MULX H2.xyz, R4.xyzx, H0.w;
DP3H H0.w, H1.xyzx, H1.xyzx;
RSQH H0.w, H0.w;
MULH H1.xyz, H0.w, H1.xyzx;
DP3X_SAT H0.x, H0.xyzx, H1.xyzx;
POWR R0.x, H0.x, specular_exponent.x;
MADR R1.xy, R0.w, R3.xyxx, f[TEX1].xyxx;
MADR R3.xy, R0.w, R3.xyxx, f[TEX3].xyxx;
TEX R2.xyz, R3.xyxx, TEX3, 2D;
TEX R1, R1.xyxx, TEX0, 2D;
MULR R2.xyz, R2.xyzx, R4.xyzx;
MULR R0.xyz, R2.xyzx, R0.x;
MULX H2.xyz, R1.xyzx, H2.xyzx;
MOVR H0.w, R1.w;
MOVX H0.xyz, H2.xyzx;
ADDH H1.xyz, H0.xyzx, R0.xyzx;
MOVH H0.xyz, H1.xyzx;
MOVH o[COLH], H0;
END
# 55 instructions, 5 R-regs, 3 H-regs.
# End of program
