!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.diffusemap
#semantic main.lightmap
#semantic main.deluxemap
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D lightmap :  : texunit 1 : 2 : 1
#var sampler2D deluxemap :  : texunit 2 : 3 : 1
#var float3 IN.normal : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 IN.tex_diffuse : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_light : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_deluxe : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var half4 main.color : $vout.COLOR : COL : -1 : 1
TEX R0.xyz, f[TEX3].xyxx, TEX2, 2D;
TEX R1.xyz, f[TEX2].xyxx, TEX1, 2D;
ADDR R0.xyz, R0.xyzx, -{0.5}.x;
MULR R0.xyz, R0.xyzx, {2}.x;
DP3R R0.w, R0.xyzx, R0.xyzx;
RSQR R0.w, R0.w;
MULR R0.xyz, R0.w, R0.xyzx;
DP3R R0.w, f[TEX0].xyzx, f[TEX0].xyzx;
RSQR R0.w, R0.w;
MULR R2.xyz, R0.w, f[TEX0].xyzx;
DP3X_SAT H0.x, R2.xyzx, R0.xyzx;
MULX H0.xyz, R1.xyzx, H0.x;
TEX R0, f[TEX1].xyxx, TEX0, 2D;
MULX H0.xyz, R0.xyzx, H0.xyzx;
MOVR H1.w, R0.w;
MOVX H1.xyz, H0.xyzx;
MOVX o[COLH], H1;
END
# 17 instructions, 3 R-regs, 2 H-regs.
# End of program
