!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.diffusemap
#semantic main.attenuationmap_xy
#semantic main.attenuationmap_z
#semantic main.light_origin
#semantic main.light_color
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D attenuationmap_xy :  : texunit 1 : 2 : 1
#var sampler2D attenuationmap_z :  : texunit 2 : 3 : 1
#var float3 light_origin :  : c[1] : 4 : 1
#var float3 light_color :  : c[0] : 5 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_diffuse : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_atten : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
PARAM u1 = program.local[1];
PARAM u0 = program.local[0];
PARAM c0 = {0, 0, 0, 1};
TEMP R0;
TEMP R1;
TEMP R2;
TEMP R3;
TEMP H0;
TEX R0, fragment.texcoord[2], texture[0], 2D;
TXP R1.xyz, fragment.texcoord[3], texture[1], 2D;
ADD R2.xyz, u1, -fragment.texcoord[0];
DP3 R2.w, R2, R2;
RSQ R2.w, R2.w;
MUL R2.xyz, R2.w, R2;
DP3 R2.w, fragment.texcoord[1], fragment.texcoord[1];
RSQ R2.w, R2.w;
MUL R3.xyz, R2.w, fragment.texcoord[1];
DP3_SAT R2.x, R3, R2;
MUL R2.xyz, u0, R2.x;
MUL R2.xyz, R0, R2;
ADD R2.w, fragment.texcoord[3].w, -c0.x;
CMP H0.x, R2.w, c0.w, c0.x;
CMP R1.xyz, -H0.x, c0, R1;
MOV R0.xyz, R2;
MUL R1.xyz, R0, R1;
MOV R0.xyz, R1;
MOV result.color, R0;
END
# 19 instructions, 4 R-regs, 1 H-regs.
# End of program
