!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.diffusemap
#semantic main.bumpmap
#semantic main.heightmap
#semantic main.lightmap
#semantic main.deluxemap
#semantic main.view_origin
#semantic main.bump_scale
#semantic main.height_scale
#semantic main.height_bias
#var sampler2D diffusemap :  : texunit 0 : 1 : 1
#var sampler2D bumpmap :  : texunit 1 : 2 : 1
#var sampler2D heightmap :  : texunit 2 : 3 : 1
#var sampler2D lightmap :  : texunit 3 : 4 : 1
#var sampler2D deluxemap :  : texunit 4 : 5 : 1
#var float3 view_origin :  :  : 6 : 1
#var float bump_scale :  :  : 7 : 1
#var float height_scale :  :  : 8 : 1
#var float height_bias :  :  : 9 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 IN.tex_diffuse_bump : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 IN.tex_height : $vin.TEXCOORD2 : TEX2 : 0 : 1
#var float4 IN.tex_light : $vin.TEXCOORD3 : TEX3 : 0 : 1
#var float4 IN.tex_deluxe : $vin.TEXCOORD4 : TEX4 : 0 : 1
#var float3 IN.tangent : $vin.TEXCOORD5 : TEX5 : 0 : 1
#var float3 IN.binormal : $vin.TEXCOORD6 : TEX6 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD7 : TEX7 : 0 : 1
#var half4 main.color : $vout.COLOR : COL : -1 : 1
DECLARE view_origin;
DECLARE bump_scale;
DECLARE height_scale;
DECLARE height_bias;
TEX R0.x, f[TEX2].xyxx, TEX2, 2D;
TEX R1.xyz, f[TEX4].xyxx, TEX4, 2D;
ADDR R1.xyz, R1.xyzx, -{0.5}.x;
MULR R1.xyz, R1.xyzx, {2}.x;
ADDR R2.xyz, view_origin.xyzx, -f[TEX0].xyzx;
DP3R R1.w, f[TEX5].xyzx, R2.xyzx;
MOVR R3.x, R1.w;
DP3R R1.w, f[TEX6].xyzx, R2.xyzx;
MOVR R3.y, R1.w;
DP3R R1.w, f[TEX7].xyzx, R2.xyzx;
MOVR R3.z, R1.w;
DP3R R1.w, R3.xyzx, R3.xyzx;
RSQR R1.w, R1.w;
MULR R3.xy, R1.w, R3.xyzx;
MOVR R1.w, height_bias.x;
MADR R1.w, R0.x, height_scale.x, R1.w;
MADR R0.xy, R1.w, R3.xyxx, f[TEX1].zwzz;
MADR R3.xy, R1.w, R3.xyxx, f[TEX1].xyxx;
TEX R0.xyz, R0.xyxx, TEX1, 2D;
TEX R2, R3.xyxx, TEX0, 2D;
ADDR R0.xyz, R0.xyzx, -{0.5}.x;
MULR R0.xyz, R0.xyzx, {2}.x;
MOVR H0.xy, R0.xyxx;
MULR R0.x, R0.z, bump_scale.x;
MOVH H0.z, R0.x;
DP3H H0.w, H0.xyzx, H0.xyzx;
RSQH H0.w, H0.w;
MULH H0.xyz, H0.w, H0.xyzx;
MOVR H1.w, R2.w;
DP3R R0.x, f[TEX5].xyzx, R1.xyzx;
DP3R R0.w, f[TEX6].xyzx, R1.xyzx;
MOVR R0.y, R0.w;
DP3R R0.w, f[TEX7].xyzx, R1.xyzx;
MOVR R0.z, R0.w;
DP3R R0.w, R0.xyzx, R0.xyzx;
RSQR R0.w, R0.w;
MULR R0.xyz, R0.w, R0.xyzx;
DP3X_SAT H0.x, H0.xyzx, R0.xyzx;
TEX R0.xyz, f[TEX3].xyxx, TEX3, 2D;
MULX H0.xyz, R0.xyzx, H0.x;
MULX H0.xyz, R2.xyzx, H0.xyzx;
MOVX H1.xyz, H0.xyzx;
MOVX o[COLH], H1;
END
# 43 instructions, 4 R-regs, 2 H-regs.
# End of program
