!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.environmentMaps
#var samplerCUBE environmentMaps[0] :  : texunit 0 : 4 : 1
#var samplerCUBE environmentMaps[1] :  : texunit 1 : 4 : 1
#var float3 color0 : $vin.COLOR0 : COL0 : 0 : 1
#var float3 color1 : $vin.COLOR1 : COL1 : 1 : 1
#var float3 reflectVec : $vin.TEXCOORD0 : TEX0 : 2 : 1
#var float3 reflectVecDark : $vin.TEXCOORD1 : TEX1 : 3 : 1
#var float4 main : $vout.COLOR : COL : -1 : 1
PARAM c0 = {0, 0, 0, 1};
TEMP R0;
TEMP R1;
TEX R0.xyz, fragment.texcoord[1], texture[1], CUBE;
TEX R1.xyz, fragment.texcoord[0], texture[0], CUBE;
MUL R0.xyz, R0, fragment.color.secondary;
MAD result.color.xyz, R1, fragment.color.primary, R0;
MOV result.color.w, c0.w;
END
# 5 instructions, 2 R-regs, 0 H-regs.
# End of program
