!!FP1.0
# NV_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile fp30
#vendor NVIDIA Corporation
#version 1.0.02
#profile fp30
#program main
#semantic main.colormap
#semantic main.view_origin
#var samplerCUBE colormap :  : texunit 0 : 1 : 1
#var float3 view_origin :  :  : 2 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var half4 main.color : $vout.COLOR : COL : -1 : 1
DECLARE view_origin;
ADDR R0.xyz, f[TEX0].xyzx, -view_origin.xyzx;
DP3R R0.w, R0.xyzx, R0.xyzx;
RSQR R0.w, R0.w;
MULR R0.xyz, R0.w, R0.xyzx;
DP3R R0.w, f[TEX1].xyzx, f[TEX1].xyzx;
RSQR R0.w, R0.w;
MULR R1.xyz, R0.w, f[TEX1].xyzx;
DP3X H0.x, R1.xyzx, R0.xyzx;
MULX H1.xyz, {1.9990234}.x, R1.xyzx;
MADX H0.xyz, -H1.xyzx, H0.x, R0.xyzx;
TEX R0.xyz, H0.xyzx, TEX0, CUBE;
MOVR o[COLH].xyz, R0.xyzx;
MOVH o[COLH].w, {0, 0, 0, 1}.w;
END
# 13 instructions, 2 R-regs, 2 H-regs.
# End of program
