!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.colormap
#semantic main.view_origin
#var samplerCUBE colormap :  : texunit 0 : 1 : 1
#var float3 view_origin :  : c[0] : 2 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
PARAM u0 = program.local[0];
PARAM c0 = {0, 0, 0, 1};
PARAM c1 = {2, 0, 0, 0};
TEMP R0;
TEMP R1;
TEMP R2;
ADD R0.xyz, fragment.texcoord[0], -u0;
DP3 R0.w, R0, R0;
RSQ R0.w, R0.w;
DP3 R1.x, fragment.texcoord[1], fragment.texcoord[1];
RSQ R1.x, R1.x;
MUL R1.xyz, R1.x, fragment.texcoord[1];
MUL R2.xyz, R0.w, R0;
DP3 R1.w, R1, R2;
MUL R1.xyz, c1.x, R1;
MUL R1.xyz, R1, R1.w;
MAD R1.xyz, R0.w, R0, -R1;
TEX R0.xyz, R1, texture[0], CUBE;
MOV result.color.xyz, R0;
MOV result.color.w, c0.w;
END
# 14 instructions, 3 R-regs, 0 H-regs.
# End of program
