!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.colormap
#semantic main.view_origin
#semantic main.refraction_index
#semantic main.fresnel_power
#semantic main.fresnel_scale
#semantic main.fresnel_bias
#var samplerCUBE colormap :  : texunit 0 : 1 : 1
#var float3 view_origin :  : c[3] : 2 : 1
#var float refraction_index :  : c[4] : 3 : 1
#var float fresnel_power :  : c[2] : 4 : 1
#var float fresnel_scale :  : c[0] : 5 : 1
#var float fresnel_bias :  : c[1] : 6 : 1
#var float4 IN.position : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float3 IN.normal : $vin.TEXCOORD1 : TEX1 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
PARAM u3 = program.local[3];
PARAM u4 = program.local[4];
PARAM u2 = program.local[2];
PARAM u0 = program.local[0];
PARAM u1 = program.local[1];
PARAM c0 = {1, 2, 0, 0};
TEMP R0;
TEMP R1;
TEMP R2;
TEMP R3;
TEMP H0;
ADD R0.xyz, fragment.texcoord[0], -u3;
DP3 R0.w, R0, R0;
RSQ R0.w, R0.w;
DP3 R1.x, fragment.texcoord[1], fragment.texcoord[1];
RSQ R1.x, R1.x;
MUL R1.xyz, R1.x, fragment.texcoord[1];
MUL R2.xyz, R0.w, R0;
DP3 R1.w, -R2, R1;
MAD R2.w, -R1.w, R1.w, c0.x;
MUL R3.x, u4.x, u4.x;
MAD R2.w, -R3.x, R2.w, c0.x;
ABS R3.x, R2.w;
RSQ R3.x, R3.x;
RCP R3.x, R3.x;
MUL R3.x, c0.x, R3.x;
MAD R3.x, u4.x, R1.w, -R3.x;
MUL R3.xyz, R3.x, R1;
ADD R2.w, c0.z, -R2.w;
CMP H0.x, R2.w, c0.x, c0.z;
MAD R3.xyz, u4.x, R2, R3;
MUL R3.xyz, R3, H0.x;
TEX R3.xyz, R3, texture[0], CUBE;
DP3 R1.w, R1, R2;
DP3 R2.x, R2, R1;
MUL R1.xyz, c0.y, R1;
MUL R1.xyz, R1, R1.w;
MAD R1.xyz, R0.w, R0, -R1;
ADD R2.x, c0.x, -R2.x;
POW R2.x, R2.x, u2.x;
TEX R0.xyz, R1, texture[0], CUBE;
ADD R0.xyz, R0, -R3;
MOV R0.w, u1.x;
MAD R0.w, R2.x, u0.x, R0.w;
MAD R0.xyz, R0.w, R0, R3;
MOV result.color.xyz, R0;
MOV result.color.w, c0.x;
END
# 36 instructions, 4 R-regs, 1 H-regs.
# End of program
