!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.1001, build date Mar 17 2004  10:58:07
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.colormap
#var sampler2D colormap :  : texunit 0 : 1 : 1
#var float4 IN.tex0 : $vin.TEXCOORD0 : TEX0 : 0 : 1
#var float4 main.color : $vout.COLOR : COL : -1 : 1
PARAM c0 = {0, 0, 0, 0};
TEMP R0;
TEX R0.w, fragment.texcoord[0], texture[0], 2D;
MOV result.color.w, R0.w;
MOV result.color.xyz, c0;
END
# 3 instructions, 1 R-regs, 0 H-regs.
# End of program
