#!/bin/bash
function check_file() {
	if [ -e $BINARY ]; then
		./$BINARY "$@"
	else
		echo "$BINARY does not exist. Please compile XreaL with scons xmap=1 first to compile."
		exit 1
	fi
}

case `uname -m` in
	x86_64)
		BINARY='xmap2.x86_64'
		check_file;
		;;
	i386|i486|i586|i686)
		BINARY='xmap2.i386'
		check_file;
		;;
	powerpc|powerpc64)
		BINARY='xmap2.ppc'
		check_file;
		;;
	"*")
		echo "You are not running a supported platform for compiling XreaL maps. If you would like to compile XreaL maps on your platform, please visit http://www.xreal-project.net for contact information."
		exit 0
		;;	
esac
