/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_Engine */

#ifndef _Included_xreal_Engine
#define _Included_xreal_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_Engine
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_Engine_print
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_Engine
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_Engine_error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xreal_Engine
 * Method:    milliseconds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xreal_Engine_milliseconds
  (JNIEnv *, jclass);

/*
 * Class:     xreal_Engine
 * Method:    consoleArgc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xreal_Engine_consoleArgc
  (JNIEnv *, jclass);

/*
 * Class:     xreal_Engine
 * Method:    consoleArgv
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_consoleArgv
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_Engine
 * Method:    consoleArgs
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_consoleArgs
  (JNIEnv *, jclass);

/*
 * Class:     xreal_Engine
 * Method:    getConfigstring
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_getConfigstring
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_Engine
 * Method:    setConfigstring
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_Engine_setConfigstring
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_Engine
 * Method:    getUserinfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_getUserinfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_Engine
 * Method:    setUserinfo
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_setUserinfo
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_Engine
 * Method:    getServerinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_Engine_getServerinfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
