/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_game_GameEntity */

#ifndef _Included_xreal_server_game_GameEntity
#define _Included_xreal_server_game_GameEntity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_game_GameEntity
 * Method:    allocateEntity0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_GameEntity_allocateEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    freeEntity0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xreal_server_game_GameEntity_freeEntity0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
