/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_game_GameEntity */

#ifndef _Included_xreal_server_game_GameEntity
#define _Included_xreal_server_game_GameEntity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_game_GameEntity
 * Method:    allocateEntity0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_GameEntity_allocateEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    freeEntity0
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xreal_server_game_GameEntity_freeEntity0
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    getEntityState_eType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_GameEntity_getEntityState_1eType
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    setEntityState_eType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_GameEntity_setEntityState_1eType
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    getEntityState_origin
 * Signature: (I)Ljavax/vecmath/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_GameEntity_getEntityState_1origin
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_GameEntity
 * Method:    setEntityState_origin
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_GameEntity_setEntityState_1origin
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
