/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_game_GameEntity */

#ifndef _Included_xreal_server_game_GameEntity
#define _Included_xreal_server_game_GameEntity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
