/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_Server */

#ifndef _Included_xreal_server_Server
#define _Included_xreal_server_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_Server
 * Method:    getConfigstring
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_server_Server_getConfigstring
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_Server
 * Method:    setConfigstring
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_Server_setConfigstring
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
