/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_game_Player */

#ifndef _Included_xreal_server_game_Player
#define _Included_xreal_server_game_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_game_Player
 * Method:    getUserInfo0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_server_game_Player_getUserInfo0
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setUserInfo0
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setUserInfo0
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_commandTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1commandTime
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_type
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1type
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_flags
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1flags
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_time
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1time
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
