/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_Engine */

#ifndef _Included_xreal_Engine
#define _Included_xreal_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_Engine
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_Engine_print
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
